CREATE TABLE FNT_FO_NOTIS_TRDS(
    fnt_seq_no	        BIGINT,		 
    fnt_mkt	            CHAR(1),	
    fnt_xchng_trd_no	BIGINT,			
    fnt_jiffy	        NUMERIC(24,2),	
    fnt_tkn	            BIGINT,			
    fnt_exctd_qty	    INTEGER,			
    fnt_exctd_rt	    DOUBLE PRECISION,		
    fnt_trd_flw	        CHAR(1),			
    fnt_ord_ack_nmbr	CHAR(20),			
    fnt_brn_cd	        BIGINT,			
    fnt_usr_id	        BIGINT,			
    fnt_pro_cli	        INTEGER,			
    fnt_clm_mtch_accnt	CHAR(10),			
    fnt_cp_cd	        CHAR(20),			
    fnt_act_typ	        INTEGER,			
    fnt_trns_cd	        CHAR(2),			
    fnt_trd_dt	        TIMESTAMP(0),			
    fnt_booktype	    CHAR(2),
    fnt_opp_tm_cd	    CHAR(20),			
    fnt_ctcl_id	        NUMERIC(30),		
    fnt_status	        CHAR(1),			
    fnt_tm_cd	        CHAR(5),			
    fnt_undrlyng	    CHAR(20),		
    fnt_ser	            CHAR(2),			
    fnt_inst	        CHAR(6),			
    fnt_expry_dt	    TIMESTAMP(0),	
    fnt_strk_prc	    DOUBLE PRECISION,			
    fnt_opt_typ	        VARCHAR(2),			
    fnt_insrt_dt	    TIMESTAMP(0),			
    fnt_run_indctr	    CHAR(1)
);

CREATE TABLE fnt_fo_notis_trds(
fnt_clm_mtch_accnt CHARACTER(10),
fnt_ord_ack_nmbr CHARACTER(20),
fnt_xchng_trd_no BIGINT,
fnt_undrlyng CHARACTER(20),
fnt_expry_dt TIMESTAMP(0) WITHOUT TIME ZONE,
fnt_opt_typ CHARACTER VARYING(2),
fnt_strk_prc BIGINT,
fnt_trd_dt TIMESTAMP(0) WITHOUT TIME ZONE,
fnt_trd_flw CHARACTER(1),
fnt_exctd_qty INTEGER,
fnt_exctd_rt BIGINT,
fnt_jiffy NUMERIC(24,2),
fnt_seq_no BIGINT,
fnt_mkt CHARACTER(1),
fnt_tkn BIGINT,
fnt_brn_cd BIGINT,
fnt_usr_id BIGINT,
fnt_pro_cli INTEGER,
fnt_cp_cd CHARACTER(20),
fnt_act_typ INTEGER,
fnt_trns_cd CHARACTER(2),
fnt_booktype CHARACTER(2),
fnt_opp_tm_cd CHARACTER(20),
fnt_ctcl_id NUMERIC(30,0),
fnt_status CHARACTER(1),
fnt_tm_cd CHARACTER(5),
fnt_ser CHARACTER(2),
fnt_inst CHARACTER(6),
fnt_insrt_dt TIMESTAMP(0) WITHOUT TIME ZONE,
fnt_run_indctr CHARACTER(1)
);